### ISSUE TITLE
Custom user icon

### ISSUE THREAD

**Issue by cohoe** [CFCC/TurboPuppet#20]
https://www.maketecheasier.com/change-default-user-account-picture-windows10/

Put files in: `C:\ProgramData\Microsoft\User Account Pictures`

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
UseDefaultTile (dword) => 1
```

**Comment by cohoe** [comment]
@idontusenumbers Can you provide PNG icons for the following sizes:
* 448 x 448 – user.png
* 192 x 192 – user-192.png
* 48 x 48 – user-48.png
* 40 x 40 – user-40.png
* 32 x 32 – user-32.png

**Comment by idontusenumbers** [comment]
Raccoon logo thing?

**Comment by cohoe** [comment]
Sure. Or something else if you so desire.

**Comment by idontusenumbers** [comment]
For the love of god, Adobe.

[profilepic.zip](https://github.com/CFCC/TurboPuppet/files/6449755/profilepic.zip)

**Comment by cohoe** [comment]
![image](https://user-images.githubusercontent.com/505621/117738749-c87bd180-b1ca-11eb-95b2-a4c49b1a05b6.png)

Well would ya look at that!

**Comment by idontusenumbers** [comment]
Cute!
