### ISSUE TITLE
Remove most (all?) the desktop shortcuts

### ISSUE THREAD

**Issue by idontusenumbers** [CFCC/TurboPuppet#4]

**Comment by cohoe** [comment]
All of our shortcuts have been relocated. Need to add notify's to all packages that install desktop shortcuts so that they get cleaned up at install-time. Don't want to wipe out the contents of the desktop at runtime because campers put things on the desktop all the time.

**Comment by cohoe** [comment]
`Get-ChildItem -Path 'C:\Users\camper\Desktop' -Filter '*.lnk' | Remove-Item` will remove shortcut files. Might be able to set this up as the notify resource.

**Comment by idontusenumbers** [comment]
We should be careful with this; users of the computer might want links on the desktop. I think my original comment was mostly about the garbage everything else put there. Probably worth just testing a puppet pull or whatever and seeing what gets added and just removing those explicitly at the end or whatever
